import Head from "next/head";
import Image from "next/image";
import Copyright from "@/components/copyright";
import Footer from "@/components/footer";
import Carousel from "react-bootstrap/Carousel";
import Other_banner from "@/components/other_banner";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Carte_pour_livre from "@/components/collection_congolaise";
import Navbar from "@/components/header";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Popup_collections from "@/components/popup_collections";

// const inter = Inter({ subsets: ["latin"] });

export default function detai_livre({ livres, auteur, livresannexs }) {
  const [buttonPopup, setButtonPopup] = useState(false);
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Popup_collections trigger={buttonPopup} setTrigger={setButtonPopup}>
          <Link
            href="../collection-congolaise"
            className="collection_congolaise"
          >
            COLLECTION CONGOLAISE →
          </Link>
          <Link
            href="../collection-internationale"
            className="collection_etrangère"
          >
            COLLECTION ETRANGRERE →
          </Link>
        </Popup_collections>

        <div className="collections_list">
          <div className="section_une">
            <div className="auteur_infos">
              <div className="avatar">
                <img
                  className="img_autors"
                  src={`http://livraze-admin.ritach.net/Views/uploads-images/auteurs/${auteur.avatar}`}
                  alt={auteur.legende}
                />

                <span>
                  <i>{auteur.legende}</i>
                </span>
              </div>
              <div className="bio">
                <h3> {auteur.nom}</h3>
                <p>{auteur.bio}</p>
              </div>
            </div>
          </div>

          <div className="section_deux">
            <div className="carousel_collections">
              <Link href="">
                <Image
                  src="/livraze_add.jpg"
                  className="caroussels_img"
                  alt="Picture of the author"
                  width={180}
                  height={200}
                  priority
                />
              </Link>
            </div>
            <div className="categories">
              {/* <h3 className="pb-5">Voir aussi</h3> */}
              <div className="livres_annexed">
                {livresannexs?.livresannexs?.slice(0, 5)?.map((item, index) => (
                  <Link href={`../livres/${item.id}`} className="titre_text">
                    <img
                      className="height_70"
                      src={`http://livraze-admin.ritach.net/Views/uploads-images/nos_livres/${item.couverture}`}
                      alt=""
                    />

                    <div className=""> {item.titre} → </div>
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>
        <div className="oeuvres">
          {" "}
          <h5> Oeuvres de {auteur.nom}</h5>
        </div>
        <div className="cards_container_n">
          <div className="livres_annexed">
            {livres?.livres?.slice(0, 5)?.map((item, index) => (
              <Link href={`../livres/${item.id}`} className="titre_text">
                <img
                  className="height_70"
                  src={`http://livraze-admin.ritach.net/Views/uploads-images/nos_livres/${item.couverture}`}
                  alt=""
                />

                <div className="titre_d_oeuvre"> {item.titre} → </div>
              </Link>
            ))}
          </div>
        </div>

        <div className="toutes_les_collections">
          <button
            onClick={() => setButtonPopup(true)}
            className="button_for_popup"
          >
            Voir toutes Nos collections →
          </button>
        </div>

        <Footer />
        <Copyright />
      </main>
    </>
  );
}

export const getServerSideProps = async ({ params }) => {
  const router = params;
  const { nom } = router;

  const request_for_unique = await fetch(
    `http://livraze-admin.ritach.net/api-v1?auteur=${nom}`
  );
  const resquest_for_all_books = await fetch(
    `http://livraze-admin.ritach.net/api-v1?livres_by_auteur=${nom}`
  );
  const annex_response = await fetch(
    "http://livraze-admin.ritach.net/api-v1?datas=livres_congolais"
  );

  const auteur = await request_for_unique.json();
  const livres = await resquest_for_all_books.json();
  const livresannexs = await annex_response.json();
  console.log("auteur: ", livresannexs);
  return {
    props: {
      auteur,
      livres,
      livresannexs,
    },
  };
};
