import Head from "next/head";
import Image from "next/image";
import Copyright from "@/components/copyright";
import Footer from "@/components/footer";
import Carousel from "react-bootstrap/Carousel";
import Other_banner from "@/components/other_banner";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Carte_pour_livre from "@/components/collection_congolaise";
import Navbar from "@/components/header";
import Link from "next/link";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

const unique_books = "http://livraze-admin.ritach.net/api-v1?livre=";
const apiurls = "http://livraze-admin.ritach.net/api-v1?datas=livres_all";

export default function detai_livre({ livre, livres }) {
  return (
    <>
      <Head>
        <title>livraze </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-livraze.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Other_banner un={livre.titre} />
        <div className="collections_list">
          <div className="section_une">
            <div className="livre_details">
              <div className="livre_containeur">
                <div className="couverture">
                  <img
                    className=""
                    src={`http://livraze-admin.ritach.net/Views/uploads-images/nos_livres/${livre.couverture}`}
                    alt=""
                  />
                </div>
                <div className="contenu">
                  <Link href={`../auteurs/${livre.authors}`}>
                    <h5>
                      {livre.maison_d_edition} | par {livre.nom} |{" "}
                      {livre.designation}
                    </h5>
                  </Link>

                  {livre.synthese}
                  <div className={styles.Carte_pour_livre_footer_n}>
                    <Link href="../tarifs" className="btn btn-success">
                      Profiter de l'offre
                    </Link>
                    <Link
                      href={`https://wa.me/+243974242040?text=Bonjour livraze, je suis  interressé(s) par le livre :${livre.titre}, Est-il disponible pour une lecture? `}
                      className={styles.whatsapp}
                    >
                      <img src="/icons/ic_lov.png" alt="" />
                      <span className="whatsapp_color"> Lire le livre </span>
                    </Link>
                  </div>
                </div>
              </div>
              <div className="synthese_livre_n"></div>

              <div className="oeuvres mt-5">
                {" "}
                <h4> Voir aussi </h4>{" "}
              </div>
              <div className="cards_container ">
                {livres?.livres?.slice(0, 5)?.map((item, index) => (
                  <Link href={`${item.id}`}>
                    <Carte_pour_livre
                      key={index}
                      nom_auteur={item.nom}
                      auteur_img_src="/icons/ecrivain.png"
                      titre_l={item.titre}
                      livre_img_src={`http://livraze-admin.ritach.net/Views/uploads-images/nos_livres/${item.couverture}`}
                    />
                  </Link>
                ))}
              </div>
            </div>
          </div>

          <div className="section_deux">
            <div className="carousel_collections">
              <Link href="">
                <Image
                  src="/livraze_add.jpg"
                  className="caroussels_img"
                  alt="Picture of the author"
                  width={180}
                  height={200}
                  priority
                />
              </Link>
            </div>
            <div className="categories">
              <h3 className="pb-5">Voir aussi </h3>
              <div className="livres_annexed">
                {livres?.livres?.slice(5, 12)?.map((item, index) => (
                  <Link href={`../livres/${item.id}`} className="titre_text">
                    <img
                      className=""
                      src={`http://livraze-admin.ritach.net/Views/uploads-images/nos_livres/${item.couverture}`}
                      alt=""
                      width={39}
                    />

                    <div className=""> {item.titre} → </div>
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>

        <Footer />
        <Copyright />
      </main>
    </>
  );
}

export const getServerSideProps = async ({ params }) => {
  const router = params;
  const { id } = router;

  const request_for_unique_book = await fetch(`${unique_books}${id}`);
  const resquest_for_all_books = await fetch(apiurls);

  const livre = await request_for_unique_book.json();
  const livres = await resquest_for_all_books.json();
  return {
    props: {
      livre,
      livres,
    },
  };
};
